"""Схемы для чек-листа партнёрства."""

from .base import (
    ChecklistCategoryBaseSchema,
    ChecklistCategoryListItemSchema,
    ChecklistCategoryWithTasksSchema,
    ChecklistTaskBaseSchema,
    ChecklistTaskListItemSchema,
)
from .requests import (
    ChecklistCategoryCreateSchema,
    ChecklistCategoryUpdateSchema,
    ChecklistTaskAssigneeUpdateSchema,
    ChecklistTaskCreateSchema,
    ChecklistTaskNotesUpdateSchema,
    ChecklistTaskStatusUpdateSchema,
    ChecklistTaskUpdateSchema,
)
from .responses import (
    ChecklistAllCategoriesWithTasksResponseSchema,
    ChecklistCategoryListResponseSchema,
    ChecklistCategoryResponseSchema,
    ChecklistCategoryWithTasksResponseSchema,
    ChecklistTaskDeleteResponseSchema,
    ChecklistTaskListResponseSchema,
    ChecklistTaskResponseSchema,
)
from .decisions import (
    AssigneeType,
    BulkDecisionValueItem,
    BulkDecisionValuesUpdateSchema,
    CategoryDecisionSummarySchema,
    DecisionFieldBaseSchema,
    DecisionFieldCreateSchema,
    DecisionFieldListItemSchema,
    DecisionFieldListResponseSchema,
    DecisionFieldResponseSchema,
    DecisionFieldSchema,
    DecisionFieldType,
    DecisionFieldUpdateSchema,
    DecisionValueUpdateSchema,
    PartnershipDecisionsResponseSchema,
    PartnershipDecisionsSummarySchema,
    SelectOptionSchema,
    TaskDecisionSummarySchema,
    ValidationRulesSchema,
)

__all__ = [
    # Base schemas
    "ChecklistCategoryBaseSchema",
    "ChecklistCategoryListItemSchema",
    "ChecklistCategoryWithTasksSchema",
    "ChecklistTaskBaseSchema",
    "ChecklistTaskListItemSchema",
    # Request schemas
    "ChecklistCategoryCreateSchema",
    "ChecklistCategoryUpdateSchema",
    "ChecklistTaskCreateSchema",
    "ChecklistTaskUpdateSchema",
    "ChecklistTaskStatusUpdateSchema",
    "ChecklistTaskNotesUpdateSchema",
    "ChecklistTaskAssigneeUpdateSchema",
    # Response schemas
    "ChecklistCategoryResponseSchema",
    "ChecklistCategoryListResponseSchema",
    "ChecklistCategoryWithTasksResponseSchema",
    "ChecklistAllCategoriesWithTasksResponseSchema",
    "ChecklistTaskResponseSchema",
    "ChecklistTaskListResponseSchema",
    "ChecklistTaskDeleteResponseSchema",
    # Decision schemas
    "AssigneeType",
    "BulkDecisionValueItem",
    "BulkDecisionValuesUpdateSchema",
    "CategoryDecisionSummarySchema",
    "DecisionFieldBaseSchema",
    "DecisionFieldCreateSchema",
    "DecisionFieldListItemSchema",
    "DecisionFieldListResponseSchema",
    "DecisionFieldResponseSchema",
    "DecisionFieldSchema",
    "DecisionFieldType",
    "DecisionFieldUpdateSchema",
    "DecisionValueUpdateSchema",
    "PartnershipDecisionsResponseSchema",
    "PartnershipDecisionsSummarySchema",
    "SelectOptionSchema",
    "TaskDecisionSummarySchema",
    "ValidationRulesSchema",
]
