"""Схемы для базы знаний."""

from .base import (
    KnowledgeArticleBaseSchema,
    KnowledgeArticleDetailSchema,
    KnowledgeArticleListItemSchema,
    KnowledgeAuthorSchema,
    KnowledgeCategoryBaseSchema,
    KnowledgeCategoryListItemSchema,
    KnowledgeChatDataSchema,
    KnowledgeChatMessageSchema,
    KnowledgeChatSourceSchema,
    KnowledgeTagBaseSchema,
    KnowledgeTagListItemSchema,
)
from .requests import (
    KnowledgeArticleCreateSchema,
    KnowledgeArticleUpdateSchema,
    KnowledgeCategoryCreateSchema,
    KnowledgeCategoryUpdateSchema,
    KnowledgeChatRequestSchema,
    KnowledgeGenerateDescriptionSchema,
    KnowledgeSearchQuerySchema,
    KnowledgeTagCreateSchema,
    KnowledgeTagUpdateSchema,
)
from .responses import (
    KnowledgeArticleDeletedSchema,
    KnowledgeArticleListResponseSchema,
    KnowledgeArticleResponseSchema,
    KnowledgeCategoryDeletedSchema,
    KnowledgeCategoryListResponseSchema,
    KnowledgeCategoryResponseSchema,
    KnowledgeChatResponseSchema,
    KnowledgeGeneratedDescriptionSchema,
    KnowledgeSearchResponseSchema,
    KnowledgeTagDeletedSchema,
    KnowledgeTagListResponseSchema,
    KnowledgeTagResponseSchema,
)

__all__ = [
    # Base
    "KnowledgeCategoryBaseSchema",
    "KnowledgeCategoryListItemSchema",
    "KnowledgeTagBaseSchema",
    "KnowledgeTagListItemSchema",
    "KnowledgeAuthorSchema",
    "KnowledgeArticleBaseSchema",
    "KnowledgeArticleListItemSchema",
    "KnowledgeArticleDetailSchema",
    "KnowledgeChatMessageSchema",
    "KnowledgeChatSourceSchema",
    # Requests
    "KnowledgeCategoryCreateSchema",
    "KnowledgeCategoryUpdateSchema",
    "KnowledgeTagCreateSchema",
    "KnowledgeTagUpdateSchema",
    "KnowledgeArticleCreateSchema",
    "KnowledgeArticleUpdateSchema",
    "KnowledgeSearchQuerySchema",
    "KnowledgeGenerateDescriptionSchema",
    "KnowledgeChatRequestSchema",
    # Responses
    "KnowledgeCategoryResponseSchema",
    "KnowledgeCategoryListResponseSchema",
    "KnowledgeTagResponseSchema",
    "KnowledgeTagListResponseSchema",
    "KnowledgeArticleResponseSchema",
    "KnowledgeArticleListResponseSchema",
    "KnowledgeSearchResponseSchema",
    "KnowledgeArticleDeletedSchema",
    "KnowledgeCategoryDeletedSchema",
    "KnowledgeTagDeletedSchema",
    "KnowledgeGeneratedDescriptionSchema",
    "KnowledgeChatResponseSchema",
    "KnowledgeChatDataSchema",
]
