"""add_users_and_roles

Revision ID: acc24a810883
Revises: 1389d76a6f81
Create Date: 2026-01-02 12:10:35.956050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'acc24a810883'
down_revision: Union[str, Sequence[str], None] = '1389d76a6f81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('username', sa.String(length=50), nullable=False, comment='Уникальное имя пользователя для входа'),
    sa.Column('email', sa.String(length=255), nullable=False, comment='Email адрес пользователя'),
    sa.Column('phone', sa.String(length=20), nullable=True, comment='Контактный телефон (опционально)'),
    sa.Column('password_hash', sa.String(length=255), nullable=True, comment='Хеш пароля'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Активен ли пользователь'),
    sa.Column('email_verified', sa.Boolean(), nullable=False, comment='Подтвержден ли email адрес'),
    sa.Column('verification_token', sa.String(length=255), nullable=True, comment='Токен для верификации email'),
    sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True, comment='Время подтверждения email'),
    sa.Column('reset_token', sa.String(length=255), nullable=True, comment='Токен для сброса пароля'),
    sa.Column('reset_token_expires_at', sa.DateTime(timezone=True), nullable=True, comment='Срок действия reset_token'),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True, comment='Последний вход в систему'),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), nullable=True, comment='Последняя активность пользователя'),
    sa.Column('full_name', sa.String(length=255), nullable=True, comment='ФИО представителя компании (опционально)'),
    sa.Column('position', sa.String(length=255), nullable=True, comment='Должность в компании'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=False)
    op.create_index(op.f('ix_users_reset_token'), 'users', ['reset_token'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_index(op.f('ix_users_verification_token'), 'users', ['verification_token'], unique=True)
    op.create_table('user_role_assignments',
    sa.Column('user_id', sa.UUID(), nullable=False, comment='ID пользователя'),
    sa.Column('role_code', sa.Enum('ADMIN', 'USER', name='rolecode'), nullable=False, comment='Код роли'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_role_assignments_role_code'), 'user_role_assignments', ['role_code'], unique=False)
    op.create_index(op.f('ix_user_role_assignments_user_id'), 'user_role_assignments', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_role_assignments_user_id'), table_name='user_role_assignments')
    op.drop_index(op.f('ix_user_role_assignments_role_code'), table_name='user_role_assignments')
    op.drop_table('user_role_assignments')
    op.drop_index(op.f('ix_users_verification_token'), table_name='users')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_reset_token'), table_name='users')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
